server:
  port: 8080

spring:
  profiles:
    default: dev
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: "x+IGkB92B98mKxe0QIi8+6eSQrjoGvvtjgHgt0SrIV+c+PbL+FpWd5jhNQv2ZJ6qhpJLA57SRkeHhdjs1koNHg=="
    expiration-minutes: 120

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/enterprise_auth?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true

app:
  cors:
    allowed-origins: "http://localhost:5500,http://127.0.0.1:5500"
